spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.3.187:3306/admin?useUnicode=true&allowMultiQueries=true&characterEncoding=UTF-8
    username: root
    password: dic*#9dc-dme58
    openMulti: true
    idle-timeout: 30000
    multi:
    - key: takeout
      type: com.zaxxer.hikari.HikariDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.3.187:3306/admin?useUnicode=true&allowMultiQueries=true&characterEncoding=UTF-8
      username: root
      password: dic*#9dc-dme58
      idle-timeout: 20000
